
package Soap.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Server", targetNamespace = "http://Soap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Server {


    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getID", targetNamespace = "http://Soap/", className = "Soap.service.GetID")
    @ResponseWrapper(localName = "getIDResponse", targetNamespace = "http://Soap/", className = "Soap.service.GetIDResponse")
    @Action(input = "http://Soap/Server/getIDRequest", output = "http://Soap/Server/getIDResponse")
    public int getID();

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "drawLine", targetNamespace = "http://Soap/", className = "Soap.service.DrawLine")
    @ResponseWrapper(localName = "drawLineResponse", targetNamespace = "http://Soap/", className = "Soap.service.DrawLineResponse")
    @Action(input = "http://Soap/Server/drawLineRequest", output = "http://Soap/Server/drawLineResponse")
    public String drawLine(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getScore", targetNamespace = "http://Soap/", className = "Soap.service.GetScore")
    @ResponseWrapper(localName = "getScoreResponse", targetNamespace = "http://Soap/", className = "Soap.service.GetScoreResponse")
    @Action(input = "http://Soap/Server/getScoreRequest", output = "http://Soap/Server/getScoreResponse")
    public String getScore();

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isGameOver", targetNamespace = "http://Soap/", className = "Soap.service.IsGameOver")
    @ResponseWrapper(localName = "isGameOverResponse", targetNamespace = "http://Soap/", className = "Soap.service.IsGameOverResponse")
    @Action(input = "http://Soap/Server/isGameOverRequest", output = "http://Soap/Server/isGameOverResponse")
    public boolean isGameOver();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGameState", targetNamespace = "http://Soap/", className = "Soap.service.GetGameState")
    @ResponseWrapper(localName = "getGameStateResponse", targetNamespace = "http://Soap/", className = "Soap.service.GetGameStateResponse")
    @Action(input = "http://Soap/Server/getGameStateRequest", output = "http://Soap/Server/getGameStateResponse")
    public String getGameState();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isItMyMove", targetNamespace = "http://Soap/", className = "Soap.service.IsItMyMove")
    @ResponseWrapper(localName = "isItMyMoveResponse", targetNamespace = "http://Soap/", className = "Soap.service.IsItMyMoveResponse")
    @Action(input = "http://Soap/Server/isItMyMoveRequest", output = "http://Soap/Server/isItMyMoveResponse")
    public boolean isItMyMove(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
